title: Home
author: Learning Turtle
email: learningturtle.yt@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
    Welcome to Learning Turtle. It is an effort to explain hard to grasp machine learning concepts in an ELI5 manner. Learners often tend to shun the theoretical side of concepts which appear difficult, this leads to gaps in fundamentals and in practice. We are trying to fill into some of these gaps. Thanks for checking us out. Cheers!
show_excerpts: true # set to true to show excerpts on the homepage
theme: texture 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Learning Turtle
  tagline: Slow and steady wins the race 
  date_format: "%b %-d, %Y"
  style: red
  search: true
  showNav: true
  showPicker: false
  disqus_shortname: learning-turtle-1
  navigation:
    - title: Home
      url: "/Blog/"
    - title: About us
      url: "/Blog/about"
  markdown: kramdown
  analytics_id: 'UA-168553113-1'
    
#header_pages:
# - about.md
  # generate social links in footer
  social_links:
    twitter:
    github: LearningTurtle 
#    linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up




# - contact.html

# Build settings
  theme: texture


plugins:
  - jekyll-seo-tag
#  - jekyll-feed
