title: Home
author: Learning Turtle
email: learningturtle.yt@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
theme: texture 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
permalink:
texture:
  title: Learning Turtle
  tagline: Slow and steady wins the race 
  date_format: "%b %-d, %Y"
  style: red
  search: false
  showNav: true
  showPicker: false
  disqus_shortname: learning-turtle-1
  navigation:
    - title: home
      url: "/Blog/"
    - title: About us
      url: ""
  markdown: kramdown
  analytics_id: 'UA-168553113-1'
    
#header_pages:
# - about.md
  # generate social links in footer
  social_links:
    twitter:
    github: https://github.com/LearningTurtle 
#    linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up




# - contact.html

# Build settings
  theme: texture


plugins:
  - jekyll-seo-tag
#  - jekyll-feed
